Repository Vibe-House-LLC/lytn.it, pull requests merged in 2025-07, with the labels that each got.

#30 Send reports to admins via ses
  amplify/auth/resource.ts
  amplify/backend.ts
  amplify/data/resource.ts
  amplify/functions/emailReportedLink/handler.ts
  amplify/functions/emailReportedLink/resource.ts
  package-lock.json
  package.json
  src/api/fetchUrl.ts
  src/api/shortenUrl.ts
  src/app/api/v2/report/createReport.ts
Labels: enhancement

#38 Fix lint errors
  src/app/api/admin/check-user/route.ts
  src/app/api/admin/debug/route.ts
  src/app/api/admin/import/route.ts
  src/app/api/admin/users-fallback/route.ts
  src/app/api/admin/users/[id]/reset-password/route.ts
  src/app/api/admin/users/[id]/route.ts
  src/app/api/admin/users/route.ts
  src/app/profile/page.tsx
  src/components/ui/textarea.tsx
  src/lib/audit-logger.ts
Labels: bug

#51 Add selection set to get shortened url query
  src/app/api/v2/report/createReport.ts
Labels: bug

#53 Fix scrolling issues
  src/app/dashboard/user/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/footer.tsx
  src/components/link-preview.tsx
Labels: bug, enhancement, codex
